cmake_minimum_required(VERSION 3.16)
project(incremental_oracle LANGUAGES CXX)
find_package(PNG REQUIRED)
find_library(HEIF_LIBRARY NAMES heif PATHS "${HEIF_BUILD_DIR}/libheif" NO_DEFAULT_PATH REQUIRED)
add_executable(primary-oracle primary-oracle.cc)
target_compile_features(primary-oracle PRIVATE cxx_std_17)
target_include_directories(primary-oracle PRIVATE "${HEIF_SOURCE_DIR}/libheif/api" "${HEIF_BUILD_DIR}")
target_link_libraries(primary-oracle PRIVATE "${HEIF_LIBRARY}" PNG::PNG)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(primary-oracle PRIVATE -Wall -Wextra -Werror)
endif()
